### ISSUE TITLE
turn off prod for now, temporarily

### ISSUE THREAD

**Issue by ingvald** [equinor/developer#51]
the simplest way, ok if url gives http 503 or something

f.eks berre skru av app service førebels

**Comment by cbuv** [comment]
how about a launch date or some text about when we're aiming to launch the site?

**Comment by ingvald** [comment]
nei, berre enklaste måte i første omgang, sa han.


________________________________

**Comment by cbuv** [comment]
slått av nå. fortsatt cachet for de som har browser vindu åpent.
